-- Docker 测试栈预置数据（真实词数 8-12，与生成链路约束一致；仅测试库执行）
-- 幂等契约：可重复执行且收敛到本文件声明的状态。含相对日期的三张指标表必须先 DELETE 本 fixture
-- 自己的行再 INSERT——只靠 INSERT IGNORE 时：唯一键含 date 的日表会跨天堆叠（9/28 与 9/30 各跑一次
-- 即得 5 个快照日，钉「3 个快照日」的 E2E 必挂）；唯一键不含 date 的表则永久保留首次运行的旧值
-- 与旧 data_date，使下方「相对值保证 7/30 天窗口内可见」的承诺随时间失效。
INSERT IGNORE INTO contents (id, template, title, level, target_duration, content, words, style, voice, audio, video, status, audit, created_at, updated_at) VALUES
('test0001scene','scene_word','测试：机场英语 错过登机','CET4',60,'[{"text": "This is a generated story sentence using flight in an everyday context.", "words": [{"word": "flight", "meaning": "释义-flight", "level": "CET4"}]}, {"text": "This is a generated story sentence using missed in an everyday context.", "words": [{"word": "missed", "meaning": "释义-missed", "level": "CET4"}]}, {"text": "This is a generated story sentence using reschedule in an everyday context.", "words": [{"word": "reschedule", "meaning": "释义-reschedule", "level": "CET4"}]}, {"text": "This is a generated story sentence using ticket in an everyday context.", "words": [{"word": "ticket", "meaning": "释义-ticket", "level": "CET4"}]}, {"text": "This is a generated story sentence using passport in an everyday context.", "words": [{"word": "passport", "meaning": "释义-passport", "level": "CET4"}]}, {"text": "This is a generated story sentence using boarding in an everyday context.", "words": [{"word": "boarding", "meaning": "释义-boarding", "level": "CET4"}]}, {"text": "This is a generated story sentence using delay in an everyday context.", "words": [{"word": "delay", "meaning": "释义-delay", "level": "CET4"}]}, {"text": "This is a generated story sentence using gate in an everyday context.", "words": [{"word": "gate", "meaning": "释义-gate", "level": "CET4"}]}]','[{"word": "flight", "meaning": "释义-flight", "level": "CET4"}, {"word": "missed", "meaning": "释义-missed", "level": "CET4"}, {"word": "reschedule", "meaning": "释义-reschedule", "level": "CET4"}, {"word": "ticket", "meaning": "释义-ticket", "level": "CET4"}, {"word": "passport", "meaning": "释义-passport", "level": "CET4"}, {"word": "boarding", "meaning": "释义-boarding", "level": "CET4"}, {"word": "delay", "meaning": "释义-delay", "level": "CET4"}, {"word": "gate", "meaning": "释义-gate", "level": "CET4"}]','{}','{}','{"url":"/files/audio/b52537e5-2f1b-4df3-b889-1f61b12ca7bf.mp3","duration":45,"format":"mp3"}','{"url":"/files/video/da40d3dc-4071-4e34-bcb0-4151781021c1.mp4","duration":48,"format":"mp4","introStatus":"rendered"}','completed','{"input": {"topic": "机场英语", "level": "CET4", "wordCount": 8, "targetDuration": 60}, "process": {"candidates": [{"source": "bank", "word": "flight"}, {"source": "bank", "word": "missed"}, {"source": "bank", "word": "reschedule"}, {"source": "bank", "word": "ticket"}, {"source": "bank", "word": "passport"}, {"source": "bank", "word": "boarding"}, {"source": "bank", "word": "delay"}, {"source": "bank", "word": "gate"}, {"source": "bank", "word": "luggage"}, {"source": "bank", "word": "check-in"}, {"source": "bank", "word": "customs"}, {"source": "bank", "word": "arrival"}], "attempts": [{"result": "rejected", "reason": "词超纲"}, {"result": "accepted", "injectedWords": ["flight", "missed", "reschedule", "ticket"]}]}, "modifications": [{"at": "2026-09-21T01:00:00Z", "fields": ["title"]}]}',NOW() - INTERVAL 10 MINUTE,NOW() - INTERVAL 5 MINUTE),
('test0002wordc','word_card','测试：职场高频词 deadline','CET4',45,'[{"word": "deadline", "pos": "n.", "meaning": "释义-deadline", "example": "The deadline matters today."}, {"word": "project", "pos": "n.", "meaning": "释义-project", "example": "The project matters today."}, {"word": "meeting", "pos": "n.", "meaning": "释义-meeting", "example": "The meeting matters today."}, {"word": "report", "pos": "n.", "meaning": "释义-report", "example": "The report matters today."}, {"word": "overtime", "pos": "n.", "meaning": "释义-overtime", "example": "The overtime matters today."}, {"word": "budget", "pos": "n.", "meaning": "释义-budget", "example": "The budget matters today."}, {"word": "client", "pos": "n.", "meaning": "释义-client", "example": "The client matters today."}, {"word": "schedule", "pos": "n.", "meaning": "释义-schedule", "example": "The schedule matters today."}]','[{"word": "deadline", "meaning": "释义-deadline", "level": "CET4"}, {"word": "project", "meaning": "释义-project", "level": "CET4"}, {"word": "meeting", "meaning": "释义-meeting", "level": "CET4"}, {"word": "report", "meaning": "释义-report", "level": "CET4"}, {"word": "overtime", "meaning": "释义-overtime", "level": "CET4"}, {"word": "budget", "meaning": "释义-budget", "level": "CET4"}, {"word": "client", "meaning": "释义-client", "level": "CET4"}, {"word": "schedule", "meaning": "释义-schedule", "level": "CET4"}]','{}','{}',NULL,NULL,'failed','{"input": {"topic": "deadline", "level": "CET4"}, "process": {"attempts": [{"result": "rejected", "reason": "词库校验失败"}]}}',NOW() - INTERVAL 30 MINUTE,NOW() - INTERVAL 2 MINUTE),
('test0003quiz0','quiz','测试：CET6 易错点','CET6',60,'[{"stem": "Choose the wrong word 0: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 1: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 2: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 3: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 4: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 5: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 6: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 7: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 8: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}, {"stem": "Choose the wrong word 9: ____", "options": ["abandon", "benefit", "capture", "deliver"], "correctIndex": 0, "explanation": "词义辨析题。", "word": {"word": "abandon", "meaning": "放弃", "level": "CET6"}}]','[{"word": "abandon", "meaning": "释义-abandon", "level": "CET6"}, {"word": "benefit", "meaning": "释义-benefit", "level": "CET6"}, {"word": "capture", "meaning": "释义-capture", "level": "CET6"}, {"word": "deliver", "meaning": "释义-deliver", "level": "CET6"}, {"word": "essence", "meaning": "释义-essence", "level": "CET6"}, {"word": "fragile", "meaning": "释义-fragile", "level": "CET6"}, {"word": "generous", "meaning": "释义-generous", "level": "CET6"}, {"word": "harmony", "meaning": "释义-harmony", "level": "CET6"}, {"word": "instinct", "meaning": "释义-instinct", "level": "CET6"}, {"word": "justice", "meaning": "释义-justice", "level": "CET6"}]','{}','{}','{"url":"/files/audio/test3.mp3","duration":30,"format":"mp3"}',NULL,'audio_ready',NULL,NOW() - INTERVAL 60 MINUTE,NOW() - INTERVAL 50 MINUTE);

-- 数据分析 Phase 2 预置：发布记录（内容 test0001scene 双平台）+ 指标（导入+派生，含每日快照）+ 账号日聚合 + 生产特征
-- 均为 INSERT IGNORE 幂等；日期用相对值保证 7/30 天窗口内可见
INSERT IGNORE INTO publish_records (id, content_id, video_asset_id, platform, platform_video_id, publish_title, publish_time, publish_status, created_at, updated_at) VALUES
('testpub0001douyin','test0001scene','da40d3dc-4071-4e34-bcb0-4151781021c1.mp4','抖音','7432123456789012345','机场英语：错过登机怎么办',NOW(),'published',NOW() - INTERVAL 2 DAY,NOW() - INTERVAL 2 DAY),
('testpub0002kuaishou','test0001scene','da40d3dc-4071-4e34-bcb0-4151781021c1.mp4','快手',NULL,'机场英语（快手未回填作品ID）',NULL,'published',NOW() - INTERVAL 3 DAY,NOW() - INTERVAL 3 DAY);
UPDATE publish_records SET publish_time = DATE_SUB(NOW(), INTERVAL 2 DAY) WHERE id='testpub0001douyin';

DELETE FROM video_metrics WHERE publish_record_id IN ('testpub0001douyin','testpub0002kuaishou');
INSERT IGNORE INTO video_metrics (publish_record_id, metric_name, metric_value, source_type, source_field, data_date, is_estimated, metadata) VALUES
('testpub0001douyin','play_count',12000,'CREATOR_IMPORT','播放量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','like_count',480,'CREATOR_IMPORT','点赞量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','comment_count',60,'CREATOR_IMPORT','评论量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','share_count',30,'CREATOR_IMPORT','分享量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','collect_count',90,'CREATOR_IMPORT','收藏量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','bounce_rate_2s',0.18,'CREATOR_IMPORT','2秒跳出率',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','watch_rate_5s',0.62,'CREATOR_IMPORT','5秒完播率',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','avg_watch_time',21.5,'CREATOR_IMPORT','平均播放时长',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','completion_rate',0.36,'CREATOR_IMPORT','完播率',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','profile_visit_count',150,'CREATOR_IMPORT','主页访问数',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL),
('testpub0001douyin','effective_play_rate_2s',0.82,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"1 - bounce_rate_2s"}'),
('testpub0001douyin','like_rate',0.04,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"like_count / play_count"}'),
('testpub0001douyin','comment_rate',0.005,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"comment_count / play_count"}'),
('testpub0001douyin','share_rate',0.0025,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"share_count / play_count"}'),
('testpub0001douyin','engagement_rate',0.0475,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"(like_count + comment_count + share_count) / play_count"}'),
('testpub0001douyin','avg_watch_ratio',0.4479,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"avg_watch_time / 视频时长（production 事实）"}'),
('testpub0001douyin','profile_visit_rate',0.0125,'PLATFORM_CALCULATED',NULL,NULL,0,'{"formula":"profile_visit_count / play_count"}'),
('testpub0002kuaishou','play_count',3000,'CREATOR_IMPORT','播放量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0,NULL);

DELETE FROM video_metric_daily WHERE publish_record_id IN ('testpub0001douyin','testpub0002kuaishou');
INSERT IGNORE INTO video_metric_daily (publish_record_id, metric_name, metric_value, source_type, source_field, data_date, is_estimated) VALUES
('testpub0001douyin','play_count',8000,'CREATOR_IMPORT','播放量',DATE_FORMAT(DATE_SUB(NOW(),INTERVAL 2 DAY),'%Y-%m-%d'),0),
('testpub0001douyin','completion_rate',0.30,'CREATOR_IMPORT','完播率',DATE_FORMAT(DATE_SUB(NOW(),INTERVAL 2 DAY),'%Y-%m-%d'),0),
('testpub0001douyin','play_count',10000,'CREATOR_IMPORT','播放量',DATE_FORMAT(DATE_SUB(NOW(),INTERVAL 1 DAY),'%Y-%m-%d'),0),
('testpub0001douyin','completion_rate',0.33,'CREATOR_IMPORT','完播率',DATE_FORMAT(DATE_SUB(NOW(),INTERVAL 1 DAY),'%Y-%m-%d'),0),
('testpub0001douyin','play_count',12000,'CREATOR_IMPORT','播放量',DATE_FORMAT(NOW(),'%Y-%m-%d'),0),
('testpub0001douyin','completion_rate',0.36,'CREATOR_IMPORT','完播率',DATE_FORMAT(NOW(),'%Y-%m-%d'),0);

DELETE FROM creator_metric_daily WHERE platform = '抖音' AND source_type = 'CREATOR_IMPORT';
INSERT IGNORE INTO creator_metric_daily (platform, stat_date, play_increment, like_increment, comment_increment, share_increment, profile_uv, new_fans, total_fans, source_type) VALUES
('抖音',DATE_FORMAT(DATE_SUB(NOW(),INTERVAL 2 DAY),'%Y-%m-%d'),8000,300,40,15,90,28,8200,'CREATOR_IMPORT'),
('抖音',DATE_FORMAT(DATE_SUB(NOW(),INTERVAL 1 DAY),'%Y-%m-%d'),2000,120,10,10,30,12,8250,'CREATOR_IMPORT'),
('抖音',DATE_FORMAT(NOW(),'%Y-%m-%d'),2000,60,10,5,30,15,8300,'CREATOR_IMPORT');

INSERT IGNORE INTO content_features (content_id, template, level, duration, knowledge_point_count, dialogue_count, segment_count, speech_rate, subtitle_type, shot_count, intro_effect, field_sources) VALUES
('test0001scene','scene_word','CET4',48,8,8,8,1,'burned_in',9,1,'{"template":"PLATFORM_PRODUCTION","level":"PLATFORM_PRODUCTION","duration":"PLATFORM_PRODUCTION","knowledge_point_count":"PLATFORM_PRODUCTION","segment_count":"PLATFORM_PRODUCTION","speech_rate":"PLATFORM_PRODUCTION","subtitle_type":"PLATFORM_PRODUCTION","shot_count":"PLATFORM_PRODUCTION","intro_effect":"PLATFORM_PRODUCTION"}');
